[project]
name = "contextual-bandit-benchmark"
version = "0.1.0"
description = "Reinforcement Learning Final Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.0",
]
